[package]
name = "useless-bot"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "0.10.1"
rusqlite = "0.30.0"
serde = "1.0.193"
